[build]
  command = "npm run build"
  publish = "dist"
  functions = ".output/server"

# Specific header for sitemap (static file)
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    content-type = "application/xml"
    X-Content-Type-Options = "nosniff"

# Remove CSP for client data JSON files to allow direct access
[[headers]]
  for = "/*-data.json"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Content-Type = "application/json; charset=utf-8"
    Access-Control-Allow-Origin = "*"

# Protect other JSON files from being accessed directly
[[headers]]
  for = "/*.json"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Content-Security-Policy = "default-src 'none'"
    Content-Type = "application/json; charset=utf-8"

# Add specific _redirects for direct JSON access
[[redirects]]
  from = "/*-data.json"
  to = "/:splat-data.json"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Handle dynamic blog routes
[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/server/blog/:splat"
  status = 200

# Handle other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = false
  conditions = {Path = {match = "\\.[a-zA-Z0-9]{2,4}$", pattern = false}}